Add postal code to customer in one line
AY2425S1-CS2103T-T13-2/tp pull request #49
Opened 2024-10-10 12:09 UTC by tohhengxing

**New features**

- Ability to add postal code to customer
- Updated GUI

2024-10-15 09:45 UTC, rimgik requested changes
Overall, the changes look solid! I just have a few minor suggestions for improvement.

2024-10-15 09:45 UTC, rimgik commented on src/main/java/seedu/address/model/person/PostalCode.java
> +    public static final String VALIDATION_REGEX = "\\d{6}";
I think postal need not to be 6 digits.

2024-10-15 09:45 UTC, rimgik commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_POSTAL_CODE = new Prefix("pc/");
Can we shorten prefix?

2024-10-15 10:41 UTC, rimgik commented on src/main/java/seedu/address/model/person/PostalCode.java
> +    public static final String VALIDATION_REGEX = "\\d{6}";
But I believe our target user does not need to be in Singapore.

2024-10-16 02:43 UTC, yyanyee commented
Looks good! Conflict resolved

2024-10-16 02:43 UTC, merged